"""baseline_m5_schema

Revision ID: c563e07756e0
Revises: 
Create Date: 2026-08-27 15:04:46.301677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c563e07756e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS reporting")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_incident_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_incident_id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.Text(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='ck_job_runs_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name', 'target_date', name='uq_job_runs_job_date'),
    schema='reporting'
    )
    op.create_table('pipeline_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('records_extracted', sa.Integer(), nullable=False),
    sa.Column('records_loaded', sa.Integer(), nullable=False),
    sa.Column('missing_cost_events_count', sa.Integer(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id'),
    schema='reporting'
    )
    op.create_table('task_dead_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('task_name', sa.Text(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reporting'
    )
    op.create_table('weekly_location_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('total_purchase_cost', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('total_waste_cost', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('waste_ratio', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('stockout_events_count', sa.Integer(), nullable=False),
    sa.Column('price_alert_events_count', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'week_start', name='uq_weekly_location_week'),
    schema='reporting'
    )
    op.create_table('rfp_metadata',
    sa.Column('rfp_id', sa.Text(), nullable=False),
    sa.Column('client_name', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('service_type', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Text(), nullable=True),
    sa.Column('budget_range', sa.Text(), nullable=True),
    sa.Column('departments_needed', sa.JSON(), nullable=True),
    sa.Column('readability_metrics', sa.JSON(), nullable=True),
    sa.Column('open_questions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rfp_id')
    )
    op.create_table('telemetry_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('service', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_events_event_id'), 'telemetry_events', ['event_id'], unique=True)
    op.create_index('ix_telemetry_events_event_type', 'telemetry_events', ['event_type'], unique=False)
    op.create_index('ix_telemetry_events_tags_gin', 'telemetry_events', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_telemetry_events_timestamp', 'telemetry_events', ['timestamp'], unique=False)
    op.create_table('ticket',
    sa.Column('ticket_id', sa.Text(), nullable=False),
    sa.Column('rfp_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('raw_pdf_path', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('owner_user_uuid', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('analyzing', 'discarded', 'intake_complete', 'drafting', 'under_evaluation', 'waiting_for_approval', 'done')", name='ck_ticket_status'),
    sa.PrimaryKeyConstraint('ticket_id'),
    sa.UniqueConstraint('content_hash', name='uq_ticket_content_hash')
    )
    op.create_index(op.f('ix_ticket_owner_user_uuid'), 'ticket', ['owner_user_uuid'], unique=False)
    op.create_index(op.f('ix_ticket_rfp_id'), 'ticket', ['rfp_id'], unique=False)
    op.create_table('department_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Text(), nullable=False),
    sa.Column('department_id', sa.Text(), nullable=False),
    sa.Column('key_aspects', sa.JSON(), nullable=True),
    sa.Column('draft_content', sa.Text(), nullable=True),
    sa.Column('evaluation_results', sa.JSON(), nullable=True),
    sa.Column('approval_status', sa.Text(), nullable=False),
    sa.Column('approver', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("approval_status IN ('pending', 'approved', 'rejected')", name='ck_department_section_approval_status'),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Text(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('total_estimated_value', sa.Text(), nullable=True),
    sa.Column('document', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingrediententry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('supplier_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredientexit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredientexit')
    op.drop_table('ingrediententry')
    op.drop_table('final_document')
    op.drop_table('department_section')
    op.drop_index(op.f('ix_ticket_rfp_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_owner_user_uuid'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_index('ix_telemetry_events_timestamp', table_name='telemetry_events')
    op.drop_index('ix_telemetry_events_tags_gin', table_name='telemetry_events', postgresql_using='gin')
    op.drop_index('ix_telemetry_events_event_type', table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_event_id'), table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_table('rfp_metadata')
    op.drop_table('weekly_location_performance', schema='reporting')
    op.drop_table('task_dead_letters', schema='reporting')
    op.drop_table('pipeline_runs', schema='reporting')
    op.drop_table('job_runs', schema='reporting')
    op.drop_table('ingredient')
    op.drop_table('incident')
    # ### end Alembic commands ###
