"""rfp_unique_department_section_final_document

Revision ID: d38c62feec63
Revises: c563e07756e0
Create Date: 2026-08-27 16:37:43.186948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd38c62feec63'
down_revision: Union[str, Sequence[str], None] = 'c563e07756e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_department_section_ticket_department', 'department_section', ['ticket_id', 'department_id'])
    op.create_unique_constraint('uq_final_document_ticket', 'final_document', ['ticket_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_final_document_ticket', 'final_document', type_='unique')
    op.drop_constraint('uq_department_section_ticket_department', 'department_section', type_='unique')
    # ### end Alembic commands ###
