-- Operator apply script: telemetry_events table on brasaland-m5.
--
-- DO NOT run from CI or agent automation against live m5.
-- Run manually on a DIRECT Postgres session (Supabase :5432 or SQL editor), not the
-- transaction pooler, unless operator confirms DDL works on pooler.
--
-- Purpose: create public.telemetry_events when m5 was stamped at Alembic baseline
-- without the table existing (ingest 500 / reporting pipeline extract failure).
--
-- Prerequisites:
--   1. Current Alembic head is f9a2b3c4d5e6 (revision telemetry_events_m5_apply).
--   2. MIGRATION_DATABASE_URL points at the m5 owner/direct URL (not runtime role).
--
-- === Preferred path: Alembic upgrade (idempotent migration) ===
--
--   cd data
--   $env:MIGRATION_DATABASE_URL = "<m5-direct-owner-url>"
--   uv run alembic upgrade head
--
-- === Post-apply verification ===
--
--   SELECT to_regclass('public.telemetry_events');  -- expect telemetry_events
--   SELECT version_num FROM public.alembic_version;  -- expect f9a2b3c4d5e6
--
--   docker compose restart telemetry reporting-worker
--   docker compose ps reporting-worker   -- expect Up, not Restarting
--
-- === Contingency: reporting-worker still Restarting with Permission denied on .venv ===
--
--   docker compose stop reporting-worker
--   docker volume rm brasaland-digital_reporting_worker_venv
--   docker compose up -d reporting-worker
--
-- === Optional SQL-editor apply (only if Alembic cannot run) ===
-- Matches data/alembic/versions/f9a2b3c4d5e6_telemetry_events_m5_apply.py when table
-- is missing. Skip if to_regclass('public.telemetry_events') is not null.
--
-- CREATE TABLE IF NOT EXISTS public.telemetry_events (
--     id INTEGER NOT NULL,
--     event_id VARCHAR NOT NULL,
--     event_type VARCHAR NOT NULL,
--     timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--     service VARCHAR NOT NULL,
--     level VARCHAR NOT NULL,
--     tags JSONB,
--     context JSONB,
--     PRIMARY KEY (id)
-- );
-- CREATE UNIQUE INDEX IF NOT EXISTS ix_telemetry_events_event_id
--     ON public.telemetry_events (event_id);
-- CREATE INDEX IF NOT EXISTS ix_telemetry_events_event_type
--     ON public.telemetry_events (event_type);
-- CREATE INDEX IF NOT EXISTS ix_telemetry_events_tags_gin
--     ON public.telemetry_events USING gin (tags);
-- CREATE INDEX IF NOT EXISTS ix_telemetry_events_timestamp
--     ON public.telemetry_events (timestamp);
--
-- After SQL-only apply, stamp Alembic if needed (operator confirms revision):
--   uv run alembic stamp f9a2b3c4d5e6
